/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

/**
 *
 * @author STUDY MODE
 */
public class EmployeeProfileInformation extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeProfileInformation
     */
    public EmployeeProfileInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new buttons.whiteButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        clothingAllowanceLabel = new javax.swing.JTextField();
        fullNameLabel = new javax.swing.JTextField();
        employeeNumberLabel = new javax.swing.JTextField();
        hourlyRateLabel = new javax.swing.JTextField();
        statusLabel = new javax.swing.JTextField();
        supervisorLabel = new javax.swing.JTextField();
        basicSalaryLabel = new javax.swing.JTextField();
        positionLabel = new javax.swing.JTextField();
        tinNumberLabel = new javax.swing.JTextField();
        sssNumberLabel = new javax.swing.JTextField();
        philhealthNumberLabel = new javax.swing.JTextField();
        pagibigNumberLabel = new javax.swing.JTextField();
        grossSemiMonthlyRateLabel = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JTextField();
        riceSubsidyLabel = new javax.swing.JTextField();
        phoneAllowanceLabel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressLabel = new javax.swing.JTextArea();
        updateInfoButton = new buttons.grayButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setText("Back");
        backButton.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Contact No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Employee No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Status");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("SSS No.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Supervisor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Position");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Hourly Rate");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Clothing Allowance");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Phone Allowance");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Birthday");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Basic Salary");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Gross Semi-Monthly Rate");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Philhealth No.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Pagibig No.");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("TIN No.");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Rice Subsidy");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, 20));

        clothingAllowanceLabel.setEditable(false);
        clothingAllowanceLabel.setBackground(new java.awt.Color(204, 204, 204));
        clothingAllowanceLabel.setForeground(new java.awt.Color(102, 102, 102));
        clothingAllowanceLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothingAllowanceLabelActionPerformed(evt);
            }
        });
        getContentPane().add(clothingAllowanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 200, -1));

        fullNameLabel.setEditable(false);
        fullNameLabel.setBackground(new java.awt.Color(204, 204, 204));
        fullNameLabel.setForeground(new java.awt.Color(102, 102, 102));
        fullNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameLabelActionPerformed(evt);
            }
        });
        getContentPane().add(fullNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 200, -1));

        employeeNumberLabel.setEditable(false);
        employeeNumberLabel.setBackground(new java.awt.Color(204, 204, 204));
        employeeNumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        employeeNumberLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNumberLabelActionPerformed(evt);
            }
        });
        getContentPane().add(employeeNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 200, -1));

        hourlyRateLabel.setEditable(false);
        hourlyRateLabel.setBackground(new java.awt.Color(204, 204, 204));
        hourlyRateLabel.setForeground(new java.awt.Color(102, 102, 102));
        hourlyRateLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyRateLabelActionPerformed(evt);
            }
        });
        getContentPane().add(hourlyRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 200, -1));

        statusLabel.setEditable(false);
        statusLabel.setBackground(new java.awt.Color(204, 204, 204));
        statusLabel.setForeground(new java.awt.Color(102, 102, 102));
        statusLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusLabelActionPerformed(evt);
            }
        });
        getContentPane().add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 200, -1));

        supervisorLabel.setEditable(false);
        supervisorLabel.setBackground(new java.awt.Color(204, 204, 204));
        supervisorLabel.setForeground(new java.awt.Color(102, 102, 102));
        supervisorLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorLabelActionPerformed(evt);
            }
        });
        getContentPane().add(supervisorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 200, -1));

        basicSalaryLabel.setEditable(false);
        basicSalaryLabel.setBackground(new java.awt.Color(204, 204, 204));
        basicSalaryLabel.setForeground(new java.awt.Color(102, 102, 102));
        basicSalaryLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicSalaryLabelActionPerformed(evt);
            }
        });
        getContentPane().add(basicSalaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 200, -1));

        positionLabel.setEditable(false);
        positionLabel.setBackground(new java.awt.Color(204, 204, 204));
        positionLabel.setForeground(new java.awt.Color(102, 102, 102));
        positionLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionLabelActionPerformed(evt);
            }
        });
        getContentPane().add(positionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, -1));

        tinNumberLabel.setEditable(false);
        tinNumberLabel.setBackground(new java.awt.Color(204, 204, 204));
        tinNumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        tinNumberLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinNumberLabelActionPerformed(evt);
            }
        });
        getContentPane().add(tinNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 200, -1));

        sssNumberLabel.setEditable(false);
        sssNumberLabel.setBackground(new java.awt.Color(204, 204, 204));
        sssNumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        sssNumberLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssNumberLabelActionPerformed(evt);
            }
        });
        getContentPane().add(sssNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 200, -1));

        philhealthNumberLabel.setEditable(false);
        philhealthNumberLabel.setBackground(new java.awt.Color(204, 204, 204));
        philhealthNumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        philhealthNumberLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                philhealthNumberLabelActionPerformed(evt);
            }
        });
        getContentPane().add(philhealthNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 200, -1));

        pagibigNumberLabel.setEditable(false);
        pagibigNumberLabel.setBackground(new java.awt.Color(204, 204, 204));
        pagibigNumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        pagibigNumberLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigNumberLabelActionPerformed(evt);
            }
        });
        getContentPane().add(pagibigNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 200, -1));

        grossSemiMonthlyRateLabel.setEditable(false);
        grossSemiMonthlyRateLabel.setBackground(new java.awt.Color(204, 204, 204));
        grossSemiMonthlyRateLabel.setForeground(new java.awt.Color(102, 102, 102));
        grossSemiMonthlyRateLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossSemiMonthlyRateLabelActionPerformed(evt);
            }
        });
        getContentPane().add(grossSemiMonthlyRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 200, -1));

        phoneNumberLabel.setEditable(false);
        phoneNumberLabel.setBackground(new java.awt.Color(204, 204, 204));
        phoneNumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        phoneNumberLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberLabelActionPerformed(evt);
            }
        });
        getContentPane().add(phoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 200, -1));

        birthdayLabel.setEditable(false);
        birthdayLabel.setBackground(new java.awt.Color(204, 204, 204));
        birthdayLabel.setForeground(new java.awt.Color(102, 102, 102));
        birthdayLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayLabelActionPerformed(evt);
            }
        });
        getContentPane().add(birthdayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 200, -1));

        riceSubsidyLabel.setEditable(false);
        riceSubsidyLabel.setBackground(new java.awt.Color(204, 204, 204));
        riceSubsidyLabel.setForeground(new java.awt.Color(102, 102, 102));
        riceSubsidyLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riceSubsidyLabelActionPerformed(evt);
            }
        });
        getContentPane().add(riceSubsidyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 200, -1));

        phoneAllowanceLabel.setEditable(false);
        phoneAllowanceLabel.setBackground(new java.awt.Color(204, 204, 204));
        phoneAllowanceLabel.setForeground(new java.awt.Color(102, 102, 102));
        phoneAllowanceLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneAllowanceLabelActionPerformed(evt);
            }
        });
        getContentPane().add(phoneAllowanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 200, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);

        addressLabel.setEditable(false);
        addressLabel.setBackground(new java.awt.Color(204, 204, 204));
        addressLabel.setColumns(20);
        addressLabel.setForeground(new java.awt.Color(102, 102, 102));
        addressLabel.setRows(5);
        jScrollPane1.setViewportView(addressLabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 200, 70));

        updateInfoButton.setText("Update Info");
        updateInfoButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        updateInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 130, -1));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\STUDY MODE\\Documents\\NetBeansProjects\\MotorPHOOP\\src\\main\\resources\\images\\Profile Information.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new EmployeePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void clothingAllowanceLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothingAllowanceLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clothingAllowanceLabelActionPerformed

    private void fullNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameLabelActionPerformed

    private void employeeNumberLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNumberLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNumberLabelActionPerformed

    private void hourlyRateLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyRateLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyRateLabelActionPerformed

    private void statusLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusLabelActionPerformed

    private void supervisorLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisorLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supervisorLabelActionPerformed

    private void basicSalaryLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicSalaryLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicSalaryLabelActionPerformed

    private void positionLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionLabelActionPerformed

    private void tinNumberLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinNumberLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinNumberLabelActionPerformed

    private void sssNumberLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssNumberLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssNumberLabelActionPerformed

    private void philhealthNumberLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_philhealthNumberLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_philhealthNumberLabelActionPerformed

    private void pagibigNumberLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibigNumberLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagibigNumberLabelActionPerformed

    private void grossSemiMonthlyRateLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grossSemiMonthlyRateLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grossSemiMonthlyRateLabelActionPerformed

    private void phoneNumberLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberLabelActionPerformed

    private void birthdayLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayLabelActionPerformed

    private void riceSubsidyLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riceSubsidyLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riceSubsidyLabelActionPerformed

    private void phoneAllowanceLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneAllowanceLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneAllowanceLabelActionPerformed

    private void updateInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoButtonActionPerformed
        // TODO add your handling code here:
        new EmployeeProfileInformationUpdateInfo().setVisible(true);
        dispose();
    }//GEN-LAST:event_updateInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfileInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfileInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfileInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfileInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeProfileInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressLabel;
    private buttons.whiteButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JTextField basicSalaryLabel;
    private javax.swing.JTextField birthdayLabel;
    private javax.swing.JTextField clothingAllowanceLabel;
    private javax.swing.JTextField employeeNumberLabel;
    private javax.swing.JTextField fullNameLabel;
    private javax.swing.JTextField grossSemiMonthlyRateLabel;
    private javax.swing.JTextField hourlyRateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pagibigNumberLabel;
    private javax.swing.JTextField philhealthNumberLabel;
    private javax.swing.JTextField phoneAllowanceLabel;
    private javax.swing.JTextField phoneNumberLabel;
    private javax.swing.JTextField positionLabel;
    private javax.swing.JTextField riceSubsidyLabel;
    private javax.swing.JTextField sssNumberLabel;
    private javax.swing.JTextField statusLabel;
    private javax.swing.JTextField supervisorLabel;
    private javax.swing.JTextField tinNumberLabel;
    private buttons.grayButton updateInfoButton;
    // End of variables declaration//GEN-END:variables
}
