/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

/**
 *
 * @author STUDY MODE
 */
public class EmployeePayslip extends javax.swing.JFrame {

    /**
     * Creates new form EmployeePayslip
     */
    public EmployeePayslip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new buttons.whiteButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        payslipMonthChooser = new com.toedter.calendar.JMonthChooser();
        jLabel8 = new javax.swing.JLabel();
        periodEndDateLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        grossIncomeLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        netSalaryLabel = new javax.swing.JLabel();
        dailyRateLabel = new javax.swing.JLabel();
        daysWorkedLabel = new javax.swing.JLabel();
        overtimeHoursLabel = new javax.swing.JLabel();
        basicSalaryLabel5 = new javax.swing.JLabel();
        witholdingTaxLabel = new javax.swing.JLabel();
        phoneAllowanceLabel = new javax.swing.JLabel();
        clothingAllowanceLabel = new javax.swing.JLabel();
        benefitsLabel = new javax.swing.JLabel();
        deductionsLabel = new javax.swing.JLabel();
        riceSubsidyLabel = new javax.swing.JLabel();
        deductions = new javax.swing.JLabel();
        philhealthDeductionLabel = new javax.swing.JLabel();
        pagibigDeductionLabel = new javax.swing.JLabel();
        sssDeductionLabel = new javax.swing.JLabel();
        grossIncome = new javax.swing.JLabel();
        benefits = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        periodStartDateLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setText("Back");
        backButton.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 40));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("SUMMARY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("TAKE HOME PAY");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("DEDUCTIONS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("BENEFITS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Period End Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        payslipMonthChooser.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        getContentPane().add(payslipMonthChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Choose Period:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        periodEndDateLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        periodEndDateLabel.setForeground(new java.awt.Color(102, 102, 102));
        periodEndDateLabel.setText("endDate();");
        getContentPane().add(periodEndDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("EARNINGS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        grossIncomeLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        grossIncomeLabel.setForeground(new java.awt.Color(102, 102, 102));
        grossIncomeLabel.setText("calculateGrossSalary();");
        getContentPane().add(grossIncomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, -1));

        jLabel12.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Daily Rate");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Days Worked");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Witholding Tax");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("GROSS INCOME");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        jLabel16.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Gross Income");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Benefits");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Deducations");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, -1, -1));

        jLabel19.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Rice Subsidy");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel20.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Phone Allowance");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jLabel21.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Clothing Allowance");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jLabel22.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("TOTAL BENEFITS");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        jLabel23.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Overtime");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel24.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Social Security System");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel25.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Philhealth");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLabel26.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Pag-Ibig");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabel27.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("TOTAL DEDUCTIONS");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jLabel28.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Monthly Rate");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        netSalaryLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        netSalaryLabel.setForeground(new java.awt.Color(102, 102, 102));
        netSalaryLabel.setText("calculateNetSalary();");
        getContentPane().add(netSalaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, -1, -1));

        dailyRateLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        dailyRateLabel.setForeground(new java.awt.Color(102, 102, 102));
        dailyRateLabel.setText("getDailyRate();");
        getContentPane().add(dailyRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        daysWorkedLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        daysWorkedLabel.setForeground(new java.awt.Color(102, 102, 102));
        daysWorkedLabel.setText("getDaysWorked();");
        getContentPane().add(daysWorkedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        overtimeHoursLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        overtimeHoursLabel.setForeground(new java.awt.Color(102, 102, 102));
        overtimeHoursLabel.setText("getOvertimeHours();");
        getContentPane().add(overtimeHoursLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        basicSalaryLabel5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        basicSalaryLabel5.setForeground(new java.awt.Color(102, 102, 102));
        basicSalaryLabel5.setText("getBasicSalary()");
        getContentPane().add(basicSalaryLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        witholdingTaxLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        witholdingTaxLabel.setForeground(new java.awt.Color(102, 102, 102));
        witholdingTaxLabel.setText("witholdingTax();");
        getContentPane().add(witholdingTaxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        phoneAllowanceLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        phoneAllowanceLabel.setForeground(new java.awt.Color(102, 102, 102));
        phoneAllowanceLabel.setText("getPhoneAllowance();");
        getContentPane().add(phoneAllowanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        clothingAllowanceLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clothingAllowanceLabel.setForeground(new java.awt.Color(102, 102, 102));
        clothingAllowanceLabel.setText("getClothingAllowance();");
        getContentPane().add(clothingAllowanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        benefitsLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        benefitsLabel.setForeground(new java.awt.Color(102, 102, 102));
        benefitsLabel.setText("calculateBenefits();");
        getContentPane().add(benefitsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        deductionsLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        deductionsLabel.setForeground(new java.awt.Color(102, 102, 102));
        deductionsLabel.setText("calculateDeductions();");
        getContentPane().add(deductionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, -1));

        riceSubsidyLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        riceSubsidyLabel.setForeground(new java.awt.Color(102, 102, 102));
        riceSubsidyLabel.setText("getRiceSubsidy();");
        getContentPane().add(riceSubsidyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        deductions.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        deductions.setForeground(new java.awt.Color(102, 102, 102));
        deductions.setText("calculateDeductions();");
        getContentPane().add(deductions, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, -1, -1));

        philhealthDeductionLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        philhealthDeductionLabel.setForeground(new java.awt.Color(102, 102, 102));
        philhealthDeductionLabel.setText("philhealthDeduction();");
        getContentPane().add(philhealthDeductionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        pagibigDeductionLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        pagibigDeductionLabel.setForeground(new java.awt.Color(102, 102, 102));
        pagibigDeductionLabel.setText("pagibigDeduction();");
        getContentPane().add(pagibigDeductionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        sssDeductionLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        sssDeductionLabel.setForeground(new java.awt.Color(102, 102, 102));
        sssDeductionLabel.setText("sssDeduction();");
        getContentPane().add(sssDeductionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        grossIncome.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        grossIncome.setForeground(new java.awt.Color(102, 102, 102));
        grossIncome.setText("calculateGrossSalary();");
        getContentPane().add(grossIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        benefits.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        benefits.setForeground(new java.awt.Color(102, 102, 102));
        benefits.setText("calculateBenefits();");
        getContentPane().add(benefits, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Period Start Date:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        periodStartDateLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        periodStartDateLabel.setForeground(new java.awt.Color(102, 102, 102));
        periodStartDateLabel.setText("startDate();");
        getContentPane().add(periodStartDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\STUDY MODE\\Documents\\NetBeansProjects\\MotorPHOOP\\src\\main\\resources\\images\\Payslip Information.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new EmployeePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePayslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private buttons.whiteButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel basicSalaryLabel5;
    private javax.swing.JLabel benefits;
    private javax.swing.JLabel benefitsLabel;
    private javax.swing.JLabel clothingAllowanceLabel;
    private javax.swing.JLabel dailyRateLabel;
    private javax.swing.JLabel daysWorkedLabel;
    private javax.swing.JLabel deductions;
    private javax.swing.JLabel deductionsLabel;
    private javax.swing.JLabel grossIncome;
    private javax.swing.JLabel grossIncomeLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel netSalaryLabel;
    private javax.swing.JLabel overtimeHoursLabel;
    private javax.swing.JLabel pagibigDeductionLabel;
    private com.toedter.calendar.JMonthChooser payslipMonthChooser;
    private javax.swing.JLabel periodEndDateLabel;
    private javax.swing.JLabel periodStartDateLabel;
    private javax.swing.JLabel philhealthDeductionLabel;
    private javax.swing.JLabel phoneAllowanceLabel;
    private javax.swing.JLabel riceSubsidyLabel;
    private javax.swing.JLabel sssDeductionLabel;
    private javax.swing.JLabel witholdingTaxLabel;
    // End of variables declaration//GEN-END:variables
}
