/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

/**
 *
 * @author STUDY MODE
 */
public class HRManagerPage extends javax.swing.JFrame {

    /**
     * Creates new form HRManagerPage
     */
    public HRManagerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new buttons.whiteButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hrManagerLeaveTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        hrManagerOvertimeTable = new javax.swing.JTable();
        approveOvertimeRequestButton = new buttons.redButton();
        rejectOvertimeRequestButton = new buttons.grayButton();
        approveLeaveRequestButton1 = new buttons.redButton();
        rejectLeaveRequestButton1 = new buttons.grayButton();
        employeeAttendanceButton = new buttons.redButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setText("Logout");
        logoutButton.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 40));

        jLabel1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Employees Overtime Request List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("HR Manager");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Employees Leave Request List");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        hrManagerLeaveTable.setBackground(new java.awt.Color(204, 204, 204));
        hrManagerLeaveTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        hrManagerLeaveTable.setForeground(new java.awt.Color(51, 51, 51));
        hrManagerLeaveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee Number", "Name", "Leave Type", "Start Date", "End Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(hrManagerLeaveTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 630, 100));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        hrManagerOvertimeTable.setBackground(new java.awt.Color(204, 204, 204));
        hrManagerOvertimeTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        hrManagerOvertimeTable.setForeground(new java.awt.Color(51, 51, 51));
        hrManagerOvertimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee Number", "Name", "Overtime Hours", "Overtime Pay", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(hrManagerOvertimeTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 630, 100));

        approveOvertimeRequestButton.setText("Approve Overtime");
        approveOvertimeRequestButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        approveOvertimeRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveOvertimeRequestButtonActionPerformed(evt);
            }
        });
        getContentPane().add(approveOvertimeRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 160, -1));

        rejectOvertimeRequestButton.setText("Reject Overtime");
        rejectOvertimeRequestButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        rejectOvertimeRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectOvertimeRequestButtonActionPerformed(evt);
            }
        });
        getContentPane().add(rejectOvertimeRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 160, -1));

        approveLeaveRequestButton1.setText("Approve Leave");
        approveLeaveRequestButton1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        approveLeaveRequestButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveLeaveRequestButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(approveLeaveRequestButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 160, -1));

        rejectLeaveRequestButton1.setText("Reject Leave");
        rejectLeaveRequestButton1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        rejectLeaveRequestButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectLeaveRequestButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(rejectLeaveRequestButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 160, -1));

        employeeAttendanceButton.setText("Employees Attendance");
        employeeAttendanceButton.setAlignmentY(0.0F);
        employeeAttendanceButton.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        employeeAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeAttendanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(employeeAttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 40));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\STUDY MODE\\Documents\\NetBeansProjects\\MotorPHOOP\\src\\main\\resources\\images\\HR Dashboard.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void approveOvertimeRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveOvertimeRequestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_approveOvertimeRequestButtonActionPerformed

    private void rejectOvertimeRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectOvertimeRequestButtonActionPerformed
        // TODO add your handling code here:
        new EmployeeOvertime().setVisible(true);
        dispose();
    }//GEN-LAST:event_rejectOvertimeRequestButtonActionPerformed

    private void approveLeaveRequestButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveLeaveRequestButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_approveLeaveRequestButton1ActionPerformed

    private void rejectLeaveRequestButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectLeaveRequestButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rejectLeaveRequestButton1ActionPerformed

    private void employeeAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeAttendanceButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_employeeAttendanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRManagerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private buttons.redButton approveLeaveRequestButton1;
    private buttons.redButton approveOvertimeRequestButton;
    private javax.swing.JLabel background;
    private buttons.redButton employeeAttendanceButton;
    private javax.swing.JTable hrManagerLeaveTable;
    private javax.swing.JTable hrManagerOvertimeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private buttons.whiteButton logoutButton;
    private buttons.grayButton rejectLeaveRequestButton1;
    private buttons.grayButton rejectOvertimeRequestButton;
    // End of variables declaration//GEN-END:variables
}
