/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

import classes.SystemAdministrator;
import classes.UserAccount;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author STUDY MODE
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginPage() {
        initComponents();
        getRootPane().setDefaultButton(loginButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButton = new buttons.redButton();
        usernameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        errorLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(960, 540));
        setName("loginPage"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setText("Login");
        loginButton.setAlignmentY(0.0F);
        loginButton.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 210, 50));

        usernameText.setBackground(new java.awt.Color(204, 204, 204));
        usernameText.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        usernameText.setForeground(new java.awt.Color(102, 102, 102));
        usernameText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });
        getContentPane().add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 320, 30));

        passwordText.setBackground(new java.awt.Color(204, 204, 204));
        passwordText.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        passwordText.setForeground(new java.awt.Color(102, 102, 102));
        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });
        passwordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTextKeyPressed(evt);
            }
        });
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 320, 30));

        errorLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(204, 0, 51));
        errorLabel.setToolTipText("");
        errorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 320, 20));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login.png"))); // NOI18N
        background.setAlignmentY(0.0F);
        background.setAutoscrolls(true);
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background.setIconTextGap(0);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
        loginButton.doClick();
    }//GEN-LAST:event_usernameTextActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String inputUsername = usernameText.getText().trim();
        String inputPassword = new String(passwordText.getPassword()).trim();

        errorLabel.setText(""); // Clear previous errors

        // Basic validation
        if (inputUsername.isEmpty()) {
            errorLabel.setText("Username/Employee Number is required!");
            return;
        }
        if (inputPassword.isEmpty()) {
            errorLabel.setText("Password is required!");
            return;
        }

        // Load all users from SystemAdministrator (joined CSVs)
        SystemAdministrator admin = new SystemAdministrator(0, "", "", "");
        String[][] allUsers = admin.getAllUsers();
        String[] matchedUser = null;

        for (String[] row : allUsers) {
            String employeeNumber = row[0];
            String username = row[19];
            String password = row[20];

            boolean matches = (employeeNumber.equalsIgnoreCase(inputUsername) || username.equalsIgnoreCase(inputUsername))
                              && password.equals(inputPassword);

            if (matches) {
                matchedUser = row;
                break;
            }
        }

        if (matchedUser == null) {
            errorLabel.setText("Invalid credentials!");
            return;
        }

        // Determine role(s)
        String[] roles = matchedUser[21].trim().toLowerCase().split("\\|");

        String selectedRole = "employee"; // default
        if (roles.length == 2) {
            for (String r : roles) {
                if (!r.equals("employee")) {
                    selectedRole = r; // override with special role
                    break;
                }
            }
        }
    
        String firstName = matchedUser[2]; // Column index 2 = First Name
        String lastName = matchedUser[1];  // Column index 1 = Last Name
        String formattedRole = formatRoleDisplay(selectedRole);

        JOptionPane.showMessageDialog(
            this,
            "Login successful.\nWelcome, " + formattedRole + ".\n" + firstName + " " + lastName,
            "MotorPH Payroll System",
            JOptionPane.INFORMATION_MESSAGE
        );

        openUserDashboard(selectedRole, matchedUser);
    }

    private void openUserDashboard(String role, String[] userData) {
        switch (role) {
            case "employee":
                new EmployeePage(userData).setVisible(true);
                break;
            case "hrmanager":
                new HRManagerPage().setVisible(true);
                break;
            case "payrollmanager":
                new PayrollManagerPage().setVisible(true);
                break;
            case "systemadministrator":
                new SystemAdministratorPage().setVisible(true);
                break;
            default:
                errorLabel.setText("Invalid role mapping!");
                return;
        }
        dispose(); // Close login window
    }//GEN-LAST:event_loginButtonActionPerformed
    
    private String formatRoleDisplay(String role) {
        switch (role.toLowerCase()) {
            case "hrmanager": return "HR Manager";
            case "payrollmanager": return "Payroll Manager";
            case "systemadministrator": return "System Administrator";
            default: return capitalize(role); // fallback
        }
    }

    private String capitalize(String input) {
        if (input == null || input.isEmpty()) return input;
        return input.substring(0, 1).toUpperCase() + input.substring(1).toLowerCase();
    }

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
        loginButton.doClick(); 
    }//GEN-LAST:event_passwordTextActionPerformed

    private void passwordTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel errorLabel;
    private buttons.redButton loginButton;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables

}
