/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

import classes.PayrollManager;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author STUDY MODE
 */
public class PayrollManagerMonthlyPayrollSummary extends javax.swing.JFrame {

    private PayrollManager payrollManager;

    public PayrollManagerMonthlyPayrollSummary() {
        initComponents();
        addListeners();
        loadPayrollSummary();
    }

    private void addListeners() {
        payrollSummaryJMonthChooser1.addPropertyChangeListener(evt -> loadPayrollSummary());
        payrollSummaryYearJChooser.addPropertyChangeListener(evt -> loadPayrollSummary());
    }

    private void loadPayrollSummary() {
        int selectedMonth = payrollSummaryJMonthChooser1.getMonth() + 1;
        int selectedYear = payrollSummaryYearJChooser.getYear();

        new Thread(() -> {
            try {
                payrollManager = new PayrollManager(selectedMonth, selectedYear);
                List<String[]> payrollData = payrollManager.processPayrollAttendance();

                DefaultTableModel model = (DefaultTableModel) payrollManagerTable.getModel();
                model.setRowCount(0);

                double totalGrossSalary = 0;
                double totalDeductions = 0;
                double totalNetSalary = 0;

                for (String[] rowData : payrollData) {
                    model.addRow(rowData);

                    try {
                        // Parse values from the table and sum up the totals
                        totalGrossSalary += Double.parseDouble(rowData[2]);
                        totalDeductions += Double.parseDouble(rowData[3]);
                        totalNetSalary += Double.parseDouble(rowData[4]);
                    } catch (NumberFormatException e) {
                        System.err.println("Error parsing salary data: " + e.getMessage());
                    }
                }

                // Update UI with computed totals
                totalGrossSalaryText.setText(String.format("%.2f", totalGrossSalary));
                totalDeductionsText.setText(String.format("%.2f", totalDeductions));
                totalNetSalaryText.setText(String.format("%.2f", totalNetSalary));

            } catch (Exception e) {
                System.err.println("Error loading payroll summary: " + e.getMessage());
            }
        }).start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new buttons.whiteButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        payrollManagerTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        totalNetSalaryText = new javax.swing.JTextField();
        totalGrossSalaryText = new javax.swing.JTextField();
        totalDeductionsText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        payrollSummaryJMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        payrollSummaryYearJChooser = new com.toedter.calendar.JYearChooser();
        jLabel6 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(960, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setText("Back");
        logoutButton.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 40));

        payrollManagerTable.setBackground(new java.awt.Color(204, 204, 204));
        payrollManagerTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        payrollManagerTable.setForeground(new java.awt.Color(51, 51, 51));
        payrollManagerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee Number", "Name", "Gross Salaries", "Deductions", "Net Salaries"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(payrollManagerTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 820, 260));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Choose Year:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        totalNetSalaryText.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        getContentPane().add(totalNetSalaryText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 380, -1));

        totalGrossSalaryText.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        getContentPane().add(totalGrossSalaryText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 170, -1));

        totalDeductionsText.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        getContentPane().add(totalDeductionsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 170, -1));

        jLabel1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("TOTAL NET SALARY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 380, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("TOTAL GROSS SALARY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("TOTAL DEDUCTIONS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Choose Payroll Month");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        payrollSummaryJMonthChooser1.setBackground(new java.awt.Color(204, 204, 204));
        payrollSummaryJMonthChooser1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(payrollSummaryJMonthChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        payrollSummaryYearJChooser.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(payrollSummaryYearJChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        jLabel6.setFont(new java.awt.Font("Inter", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("(Select Month and Year to display the Payroll List. There may be a slight delay, so please wait for the result.)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Payroll Manager Payroll Summary.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        new PayrollManagerPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerMonthlyPayrollSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerMonthlyPayrollSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerMonthlyPayrollSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerMonthlyPayrollSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollManagerMonthlyPayrollSummary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private buttons.whiteButton logoutButton;
    private javax.swing.JTable payrollManagerTable;
    private com.toedter.calendar.JMonthChooser payrollSummaryJMonthChooser1;
    private com.toedter.calendar.JYearChooser payrollSummaryYearJChooser;
    private javax.swing.JTextField totalDeductionsText;
    private javax.swing.JTextField totalGrossSalaryText;
    private javax.swing.JTextField totalNetSalaryText;
    // End of variables declaration//GEN-END:variables
}
