/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author STUDY MODE
 */
public class PayrollManagerPage extends javax.swing.JFrame {
    
    private String[] employeeData;
    /**
     * Creates new form PayrollManagerPage
     */
    public PayrollManagerPage() {      
        startRealTimeClock();
        initComponents();
        populateEmployeeInfo();
    }
    
    public PayrollManagerPage(String[] employeeData) {
        this.employeeData = employeeData;
        startRealTimeClock();
        initComponents();
        populateEmployeeInfo();
    }
    
    // Method to populate employee information on the GUI
    private void populateEmployeeInfo() {
        if (employeeData == null || employeeData.length != 22) {
            System.out.println("Error: Incorrect employee data format.");
            return;
        }

        nameProfileLabel.setText(employeeData[2] + " " + employeeData[1]);
        positionProfileLabel.setText(employeeData[11]);
    }    
    
    private void startRealTimeClock() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LocalDateTime now = LocalDateTime.now(); 
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"); 
                dateTimeProfileLabel.setText(now.format(formatter)); 
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new buttons.whiteButton();
        profileInformationButton = new buttons.redButton();
        dateTimeProfileLabel = new javax.swing.JLabel();
        employeeRoleButton = new buttons.grayButton();
        nameProfileLabel = new javax.swing.JLabel();
        positionProfileLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(960, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setText("Logout");
        logoutButton.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 40));

        profileInformationButton.setText("Payroll Summary");
        profileInformationButton.setAlignmentY(0.0F);
        profileInformationButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        profileInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileInformationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(profileInformationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 160, 40));

        dateTimeProfileLabel.setFont(new java.awt.Font("Inter", 0, 48)); // NOI18N
        dateTimeProfileLabel.setForeground(new java.awt.Color(102, 102, 102));
        dateTimeProfileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTimeProfileLabel.setText("Date & Time");
        dateTimeProfileLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(dateTimeProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 620, 100));

        employeeRoleButton.setText("Switch to Employee Role");
        employeeRoleButton.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        employeeRoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeRoleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(employeeRoleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 40));

        nameProfileLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        nameProfileLabel.setForeground(new java.awt.Color(102, 102, 102));
        nameProfileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameProfileLabel.setText("Name");
        getContentPane().add(nameProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 230, 140, -1));

        positionProfileLabel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        positionProfileLabel.setForeground(new java.awt.Color(102, 102, 102));
        positionProfileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionProfileLabel.setText("Position");
        positionProfileLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(positionProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Manager Dashboard.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Do you really want to log out of your session?",
            "MotorPH Payroll System - Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            new LoginPage().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void profileInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileInformationButtonActionPerformed
        // TODO add your handling code here:
        new PayrollManagerMonthlyPayrollSummary(employeeData).setVisible(true);
        dispose();
    }//GEN-LAST:event_profileInformationButtonActionPerformed

    private void employeeRoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeRoleButtonActionPerformed
        if (employeeData != null) {
            new EmployeePage(employeeData).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_employeeRoleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollManagerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel dateTimeProfileLabel;
    private buttons.grayButton employeeRoleButton;
    private buttons.whiteButton logoutButton;
    private javax.swing.JLabel nameProfileLabel;
    private javax.swing.JLabel positionProfileLabel;
    private buttons.redButton profileInformationButton;
    // End of variables declaration//GEN-END:variables
}
